name: backend-services
region: AMS3
size: s-2vcpu-4gb
image: ubuntu-24-04-x64
enable_backups: false
enable_ipv6: false
user_data: null
private_networking: null
volumes: null
enable_monitoring: true
tags:
  - lettergun
  - backend
  - database
